name: Deploy to Cloud Run on Merge

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    deploy:
        name: Deploy to Cloud Run
        runs-on: ubuntu-latest
        steps:

        - name: Checkout repository
          uses: actions/checkout@v2

        - id: 'auth'
          uses: 'google-github-actions/auth@v0'
          with:
            credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v0'

        - name: Deploy Docker image
          run: gcloud run deploy ${{ secrets.GCP_APP_NAME }} --source . --region australia-southeast2